/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import javax.swing.JDesktopPane;
import javax.swing.JMenuItem;

/**
 *
 * @author Roy Morocho <roymorocho at gmail.com>
 */
public class VPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form V_PRINCIPAL
     */
    public VPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dtp_principal = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jm_mantenimiento = new javax.swing.JMenu();
        ItemUsuario = new javax.swing.JMenuItem();
        ItemEmpleado = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        item_logout = new javax.swing.JMenuItem();
        Item_salir = new javax.swing.JMenuItem();
        jm_consultas = new javax.swing.JMenu();
        Citem_usuario = new javax.swing.JMenuItem();
        Citem_Clientes = new javax.swing.JMenuItem();
        Citem_vehiculos = new javax.swing.JMenuItem();
        Citem_trabajadores = new javax.swing.JMenuItem();
        jm_reportes = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jm_info = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dtp_principal.setBackground(new java.awt.Color(230, 235, 240));
        dtp_principal.setForeground(new java.awt.Color(230, 235, 240));
        dtp_principal.setToolTipText("");
        dtp_principal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        dtp_principal.setDesktopManager(null);

        javax.swing.GroupLayout dtp_principalLayout = new javax.swing.GroupLayout(dtp_principal);
        dtp_principal.setLayout(dtp_principalLayout);
        dtp_principalLayout.setHorizontalGroup(
            dtp_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1366, Short.MAX_VALUE)
        );
        dtp_principalLayout.setVerticalGroup(
            dtp_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 675, Short.MAX_VALUE)
        );

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(44, 73, 114));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Se requiere iniciar sesión");
        jLabel1.setToolTipText("");

        jMenuBar1.setBackground(new java.awt.Color(30, 45, 85));
        jMenuBar1.setForeground(new java.awt.Color(30, 45, 85));

        jm_mantenimiento.setBackground(new java.awt.Color(30, 45, 85));
        jm_mantenimiento.setText("Mantenimiento");

        ItemUsuario.setBackground(new java.awt.Color(44, 73, 114));
        ItemUsuario.setText("Nuevo usuario");
        ItemUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemUsuarioActionPerformed(evt);
            }
        });
        jm_mantenimiento.add(ItemUsuario);

        ItemEmpleado.setBackground(new java.awt.Color(44, 73, 114));
        ItemEmpleado.setText("Nuevo Empleado");
        jm_mantenimiento.add(ItemEmpleado);
        jm_mantenimiento.add(jSeparator1);

        item_logout.setBackground(new java.awt.Color(44, 73, 114));
        item_logout.setText("Cerrar sesión");
        item_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_logoutActionPerformed(evt);
            }
        });
        jm_mantenimiento.add(item_logout);

        Item_salir.setBackground(new java.awt.Color(44, 73, 114));
        Item_salir.setText("Salir");
        jm_mantenimiento.add(Item_salir);

        jMenuBar1.add(jm_mantenimiento);

        jm_consultas.setBackground(new java.awt.Color(30, 45, 85));
        jm_consultas.setText("Consultas");

        Citem_usuario.setBackground(new java.awt.Color(44, 73, 114));
        Citem_usuario.setText("Usuarios");
        Citem_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Citem_usuarioActionPerformed(evt);
            }
        });
        jm_consultas.add(Citem_usuario);

        Citem_Clientes.setBackground(new java.awt.Color(44, 73, 114));
        Citem_Clientes.setText("Clientes");
        jm_consultas.add(Citem_Clientes);

        Citem_vehiculos.setBackground(new java.awt.Color(44, 73, 114));
        Citem_vehiculos.setText("Vehículos");
        jm_consultas.add(Citem_vehiculos);

        Citem_trabajadores.setBackground(new java.awt.Color(44, 73, 114));
        Citem_trabajadores.setText("Trabajadores");
        Citem_trabajadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Citem_trabajadoresActionPerformed(evt);
            }
        });
        jm_consultas.add(Citem_trabajadores);

        jMenuBar1.add(jm_consultas);

        jm_reportes.setBackground(new java.awt.Color(30, 45, 85));
        jm_reportes.setText("Reportes");

        jMenuItem7.setBackground(new java.awt.Color(44, 73, 114));
        jMenuItem7.setText("Clientes");
        jm_reportes.add(jMenuItem7);

        jMenuItem4.setBackground(new java.awt.Color(44, 73, 114));
        jMenuItem4.setText("Usuarios");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jm_reportes.add(jMenuItem4);

        jMenuBar1.add(jm_reportes);

        jm_info.setBackground(new java.awt.Color(30, 45, 85));
        jm_info.setText("Info");
        jMenuBar1.add(jm_info);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dtp_principal)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(dtp_principal)
                .addGap(0, 0, 0)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ItemUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemUsuarioActionPerformed

    private void item_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_logoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_item_logoutActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void Citem_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Citem_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Citem_usuarioActionPerformed

    private void Citem_trabajadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Citem_trabajadoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Citem_trabajadoresActionPerformed

    public JDesktopPane getDtp_principal() {
        return dtp_principal;
    }

    public void setDtp_principal(JDesktopPane dtp_principal) {
        this.dtp_principal = dtp_principal;
    }

    public JMenuItem getItemUsuario() {
        return ItemUsuario;
    }

    public void setItemUsuario(JMenuItem ItemUsuario) {
        this.ItemUsuario = ItemUsuario;
    }

    public JMenuItem getItemEmpleado() {
        return ItemEmpleado;
    }

    public void setItemEmpleado(JMenuItem ItemEmpleado) {
        this.ItemEmpleado = ItemEmpleado;
    }

    public JMenuItem getCitem_Clientes() {
        return Citem_Clientes;
    }

    public void setCitem_Clientes(JMenuItem Citem_Clientes) {
        this.Citem_Clientes = Citem_Clientes;
    }

    public JMenuItem getCitem_trabajadores() {
        return Citem_trabajadores;
    }

    public void setCitem_trabajadores(JMenuItem Citem_trabajadores) {
        this.Citem_trabajadores = Citem_trabajadores;
    }

    public JMenuItem getCitem_usuario() {
        return Citem_usuario;
    }

    public void setCitem_usuario(JMenuItem Citem_usuario) {
        this.Citem_usuario = Citem_usuario;
    }

    public JMenuItem getCitem_vehiculos() {
        return Citem_vehiculos;
    }

    public void setCitem_vehiculos(JMenuItem Citem_vehiculos) {
        this.Citem_vehiculos = Citem_vehiculos;
    }

    public JMenuItem getItem_salir() {
        return Item_salir;
    }

    public void setItem_salir(JMenuItem Item_salir) {
        this.Item_salir = Item_salir;
    }

    public JMenuItem getItem_logout() {
        return item_logout;
    }

    public void setItem_logout(JMenuItem item_logout) {
        this.item_logout = item_logout;
    }

//    
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(VPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(VPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(VPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(VPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new VPrincipal().setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Citem_Clientes;
    private javax.swing.JMenuItem Citem_trabajadores;
    private javax.swing.JMenuItem Citem_usuario;
    private javax.swing.JMenuItem Citem_vehiculos;
    private javax.swing.JMenuItem ItemEmpleado;
    private javax.swing.JMenuItem ItemUsuario;
    private javax.swing.JMenuItem Item_salir;
    private javax.swing.JDesktopPane dtp_principal;
    private javax.swing.JMenuItem item_logout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenu jm_consultas;
    private javax.swing.JMenu jm_info;
    private javax.swing.JMenu jm_mantenimiento;
    private javax.swing.JMenu jm_reportes;
    // End of variables declaration//GEN-END:variables
}
